### ISSUE TITLE
Standardize to a dev environment?

### ISSUE THREAD

**Issue by n8han** [meetup/meetup-scala-class#1]
Just noticed in the first paragraph

> You can launch an interactive REPL (a read evaluate print loop) by running the `./sbt console` command

But I think I would ask people to use their devboxes and run `/usr/local/meetup/tools/sbt` just so there is no prior setup required. Actually having that on the executable path is a vague aspiration of mine, but for now I'm in favor of long paths that just work.

What do other people think?

**Comment by non** [comment]
Obviously we ended up open-sourcing this and using a generic configuration. Closing this.
